DROP TABLE IF EXISTS credit_apply;
DROP TABLE IF EXISTS customer_credit_score;
DROP TABLE IF EXISTS customer;

CREATE TABLE customer
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    national_id    VARCHAR(11)  NOT NULL UNIQUE,
    firstname VARCHAR(25)   NOT NULL,
    lastname  VARCHAR(25)   NOT NULL,
    monthly_income INT NOT NULL,
    phone     VARCHAR(10) NOT NULL
);
CREATE TABLE credit_apply
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_national_id VARCHAR(11) NOT NULL,
    is_application_approved BOOLEAN NOT NULL,
    credit_limit INT,
    apply_date TIMESTAMP,
    FOREIGN KEY (customer_national_id) REFERENCES customer (national_id)
);
CREATE TABLE customer_credit_score
(
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_national_id VARCHAR(11) NOT NULL UNIQUE,
    credit_score INT NOT NULL,
    FOREIGN KEY (customer_national_id) REFERENCES customer (national_id)
);

INSERT INTO customer(national_id,firstname, lastname, monthly_income, phone)
VALUES (18012123340,'Ali', 'Tek', 6600, '5356768890'),
(12132334568,'Ceren', 'Telli', 5760, '5304868872'),
(54576741520,'Dilek', 'Tutku', 7590, '5385264071'),
(12232768902,'Selin', 'Şanlı', 10040, '5324046683'),
(43456709016,'Veli', 'Yılmaz', 12500, '5402160842'),
(21386906512,'Burak', 'Kaplan', 8500, '5305453421'),
(89674332218,'Murat', 'Yıldız', 4250, '5452124909'),
(32312678894,'Elif', 'Karakurt', 15050, '5432098795'),
(34234589006,'Ozan', 'Savas', 18250, '5036578489'),
(60382431654,'Ahmet', 'Vardar', 9580, '5348786500');

INSERT INTO customer_credit_score(customer_national_id,credit_score)
VALUES (18012123340, 400),
(12132334568,600),
(54576741520,1500),
(12232768902,1800),
(43456709016,700),
(60382431654,300);